/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/sanity/extract.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type SocialLink = {
  _type: "socialLink";
  label?: string;
  url?: string;
};

export type FilmClip = {
  _type: "filmClip";
  label?: string;
  video?: MuxVideo;
};

export type Credit = {
  _type: "credit";
  role?: string;
  name?: string;
  url?: string;
};

export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: "inlineImage";
      _key: string;
    }
>;

export type InfoPage = {
  _id: string;
  _type: "infoPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  bio?: RichText;
  portrait?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  clients?: Array<string>;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  tagline?: string;
  description?: string;
  lettermark?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  favicon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  email?: string;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  resume?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  client?: string;
  date?: string;
  summary?: string;
  body?: RichText;
  video?: MuxVideo;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  loop?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  roles?: Array<string>;
  credits?: Array<
    {
      _key: string;
    } & Credit
  >;
  additionalVideos?: Array<
    {
      _key: string;
    } & FilmClip
  >;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  externalUrl?: string;
  featured?: boolean;
  hidden?: boolean;
  orderRank?: number;
  seo?: Seo;
};

export type MuxVideoAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "mux.videoAsset";
};

export type MuxVideo = {
  _type: "mux.video";
  asset?: MuxVideoAssetReference;
};

export type MuxVideoAsset = {
  _id: string;
  _type: "mux.videoAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  status?: string;
  assetId?: string;
  playbackId?: string;
  filename?: string;
  thumbTime?: number;
  data?: MuxAssetData;
};

export type MuxAssetData = {
  _type: "mux.assetData";
  resolution_tier?: string;
  upload_id?: string;
  created_at?: string;
  id?: string;
  status?: string;
  max_stored_resolution?: string;
  passthrough?: string;
  encoding_tier?: string;
  video_quality?: string;
  master_access?: string;
  aspect_ratio?: string;
  duration?: number;
  max_stored_frame_rate?: number;
  mp4_support?: string;
  max_resolution_tier?: string;
  tracks?: Array<
    {
      _key: string;
    } & MuxTrack
  >;
  playback_ids?: Array<
    {
      _key: string;
    } & MuxPlaybackId
  >;
  static_renditions?: MuxStaticRenditions;
  master?: MuxMasterFile;
};

export type MuxMasterFile = {
  _type: "mux.masterFile";
  status?: string;
  url?: string;
};

export type MuxStaticRenditions = {
  _type: "mux.staticRenditions";
  status?: string;
  files?: Array<
    {
      _key: string;
    } & MuxStaticRenditionFile
  >;
};

export type MuxStaticRenditionFile = {
  _type: "mux.staticRenditionFile";
  name?: string;
  ext?: string;
  height?: number;
  width?: number;
  bitrate?: number;
  filesize?: string;
  type?: string;
  status?: string;
  resolution_tier?: string;
  resolution?: string;
  id?: string;
  passthrough?: string;
};

export type MuxPlaybackId = {
  _type: "mux.playbackId";
  id?: string;
  policy?: string;
};

export type MuxTrack = {
  _type: "mux.track";
  id?: string;
  type?: string;
  max_width?: number;
  max_frame_rate?: number;
  duration?: number;
  max_height?: number;
  language_code?: string;
  name?: string;
  status?: string;
  text_source?: string;
  text_type?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Seo
  | SocialLink
  | FilmClip
  | Credit
  | RichText
  | InfoPage
  | SanityImageCrop
  | SanityImageHotspot
  | SanityFileAssetReference
  | SiteSettings
  | Category
  | Slug
  | CategoryReference
  | Project
  | MuxVideoAssetReference
  | MuxVideo
  | MuxVideoAsset
  | MuxAssetData
  | MuxMasterFile
  | MuxStaticRenditions
  | MuxStaticRenditionFile
  | MuxPlaybackId
  | MuxTrack
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && hidden != true] | order(coalesce(orderRank, 999999) asc, date desc) {    _id,    title,    "slug": slug.current,    client,    date,    summary,    featured,    roles,    poster {   asset,  hotspot,  crop,  alt,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions },    "loopUrl": loop.asset->url,    video {   "playbackId": asset->playbackId,  "aspectRatio": asset->data.aspect_ratio,  "duration": asset->data.duration,  "status": asset->status }  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  client: string | null;
  date: string | null;
  summary: string | null;
  featured: boolean | null;
  roles: Array<string> | null;
  poster: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
    lqip: string | null;
    dimensions: SanityImageDimensions | null;
  } | null;
  loopUrl: string | null;
  video: {
    playbackId: string | null;
    aspectRatio: string | null;
    duration: number | null;
    status: string | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    client,    date,    summary,    body[] {      ...,      _type == "inlineImage" => {   asset,  hotspot,  crop,  alt,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions, caption },      markDefs[] { ... }    },    roles,    credits[] { _key, role, name, url },    categories[]-> { _id, title, "slug": slug.current },    externalUrl,    poster {   asset,  hotspot,  crop,  alt,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions },    gallery[] { _key,   asset,  hotspot,  crop,  alt,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions, caption },    video {   "playbackId": asset->playbackId,  "aspectRatio": asset->data.aspect_ratio,  "duration": asset->data.duration,  "status": asset->status },    additionalVideos[] { _key, label, video {   "playbackId": asset->playbackId,  "aspectRatio": asset->data.aspect_ratio,  "duration": asset->data.duration,  "status": asset->status } },    seo { title, description, noIndex, image {   asset,  hotspot,  crop,  alt,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions } }  }
export type PROJECT_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  client: string | null;
  date: string | null;
  summary: string | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }> | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset: SanityImageAssetReference | null;
        media?: unknown;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string | null;
        caption: string | null;
        _type: "inlineImage";
        _key: string;
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
        markDefs: null;
      }
  > | null;
  roles: Array<string> | null;
  credits: Array<{
    _key: string;
    role: string | null;
    name: string | null;
    url: string | null;
  }> | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  externalUrl: string | null;
  poster: {
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
    lqip: string | null;
    dimensions: SanityImageDimensions | null;
  } | null;
  gallery: Array<{
    _key: string;
    asset: SanityImageAssetReference | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    alt: string | null;
    lqip: string | null;
    dimensions: SanityImageDimensions | null;
    caption: string | null;
  }> | null;
  video: {
    playbackId: string | null;
    aspectRatio: string | null;
    duration: number | null;
    status: string | null;
  } | null;
  additionalVideos: Array<{
    _key: string;
    label: string | null;
    video: {
      playbackId: string | null;
      aspectRatio: string | null;
      duration: number | null;
      status: string | null;
    } | null;
  }> | null;
  seo: {
    title: string | null;
    description: string | null;
    noIndex: boolean | null;
    image: {
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      crop: SanityImageCrop | null;
      alt: null;
      lqip: string | null;
      dimensions: SanityImageDimensions | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECT_ORDER_QUERY
// Query: *[_type == "project" && hidden != true] | order(coalesce(orderRank, 999999) asc, date desc) {    title,    "slug": slug.current  }
export type PROJECT_ORDER_QUERY_RESULT = Array<{
  title: string | null;
  slug: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)].slug.current
export type PROJECT_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: src/sanity/lib/queries.ts
// Variable: SITEMAP_QUERY
// Query: *[_type == "project" && hidden != true && defined(slug.current)] {    "slug": slug.current,    _updatedAt  }
export type SITEMAP_QUERY_RESULT = Array<{
  slug: string | null;
  _updatedAt: string;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0] {    title,    tagline,    description,    email,    socialLinks[] { _key, label, url },    lettermark {   asset,  hotspot,  crop,  alt,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions },    ogImage {   asset,  hotspot,  crop,  alt,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions },    "resumeUrl": resume.asset->url  }
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      title: null;
      tagline: null;
      description: null;
      email: null;
      socialLinks: null;
      lettermark: null;
      ogImage: null;
      resumeUrl: null;
    }
  | {
      title: string | null;
      tagline: null;
      description: null;
      email: null;
      socialLinks: null;
      lettermark: null;
      ogImage: null;
      resumeUrl: null;
    }
  | {
      title: string | null;
      tagline: null;
      description: string | null;
      email: null;
      socialLinks: null;
      lettermark: null;
      ogImage: null;
      resumeUrl: null;
    }
  | {
      title: string | null;
      tagline: string | null;
      description: string | null;
      email: string | null;
      socialLinks: Array<{
        _key: string;
        label: string | null;
        url: string | null;
      }> | null;
      lettermark: {
        asset: SanityImageAssetReference | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: null;
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
      ogImage: {
        asset: SanityImageAssetReference | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: null;
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
      resumeUrl: string | null;
    }
  | null;

// Source: src/sanity/lib/queries.ts
// Variable: INFO_PAGE_QUERY
// Query: *[_id == "infoPage"][0] {    heading,    bio[] {      ...,      _type == "inlineImage" => {   asset,  hotspot,  crop,  alt,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions, caption },      markDefs[] { ... }    },    portrait {   asset,  hotspot,  crop,  alt,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions },    clients,    seo { title, description, noIndex, image {   asset,  hotspot,  crop,  alt,  "lqip": asset->metadata.lqip,  "dimensions": asset->metadata.dimensions } }  }
export type INFO_PAGE_QUERY_RESULT =
  | {
      heading: null;
      bio: null;
      portrait: null;
      clients: null;
      seo: null;
    }
  | {
      heading: null;
      bio: null;
      portrait: null;
      clients: null;
      seo: {
        title: string | null;
        description: string | null;
        noIndex: boolean | null;
        image: {
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: null;
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    }
  | {
      heading: string | null;
      bio: Array<
        | {
            children?: Array<{
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }>;
            style?: "blockquote" | "h2" | "h3" | "normal";
            listItem?: "bullet" | "number";
            markDefs: Array<{
              href?: string;
              _type: "link";
              _key: string;
            }> | null;
            level?: number;
            _type: "block";
            _key: string;
          }
        | {
            asset: SanityImageAssetReference | null;
            media?: unknown;
            hotspot: SanityImageHotspot | null;
            crop: SanityImageCrop | null;
            alt: string | null;
            caption: string | null;
            _type: "inlineImage";
            _key: string;
            lqip: string | null;
            dimensions: SanityImageDimensions | null;
            markDefs: null;
          }
      > | null;
      portrait: {
        asset: SanityImageAssetReference | null;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string | null;
        lqip: string | null;
        dimensions: SanityImageDimensions | null;
      } | null;
      clients: Array<string> | null;
      seo: {
        title: string | null;
        description: string | null;
        noIndex: boolean | null;
        image: {
          asset: SanityImageAssetReference | null;
          hotspot: SanityImageHotspot | null;
          crop: SanityImageCrop | null;
          alt: null;
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "project" && hidden != true] | order(coalesce(orderRank, 999999) asc, date desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    client,\n    date,\n    summary,\n    featured,\n    roles,\n    poster { \n  asset,\n  hotspot,\n  crop,\n  alt,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n },\n    "loopUrl": loop.asset->url,\n    video { \n  "playbackId": asset->playbackId,\n  "aspectRatio": asset->data.aspect_ratio,\n  "duration": asset->data.duration,\n  "status": asset->status\n }\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    client,\n    date,\n    summary,\n    body[] {\n      ...,\n      _type == "inlineImage" => { \n  asset,\n  hotspot,\n  crop,\n  alt,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n, caption },\n      markDefs[] { ... }\n    },\n    roles,\n    credits[] { _key, role, name, url },\n    categories[]-> { _id, title, "slug": slug.current },\n    externalUrl,\n    poster { \n  asset,\n  hotspot,\n  crop,\n  alt,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n },\n    gallery[] { _key, \n  asset,\n  hotspot,\n  crop,\n  alt,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n, caption },\n    video { \n  "playbackId": asset->playbackId,\n  "aspectRatio": asset->data.aspect_ratio,\n  "duration": asset->data.duration,\n  "status": asset->status\n },\n    additionalVideos[] { _key, label, video { \n  "playbackId": asset->playbackId,\n  "aspectRatio": asset->data.aspect_ratio,\n  "duration": asset->data.duration,\n  "status": asset->status\n } },\n    seo { title, description, noIndex, image { \n  asset,\n  hotspot,\n  crop,\n  alt,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n } }\n  }\n': PROJECT_QUERY_RESULT;
    '\n  *[_type == "project" && hidden != true] | order(coalesce(orderRank, 999999) asc, date desc) {\n    title,\n    "slug": slug.current\n  }\n': PROJECT_ORDER_QUERY_RESULT;
    '\n  *[_type == "project" && defined(slug.current)].slug.current\n': PROJECT_SLUGS_QUERY_RESULT;
    '\n  *[_type == "project" && hidden != true && defined(slug.current)] {\n    "slug": slug.current,\n    _updatedAt\n  }\n': SITEMAP_QUERY_RESULT;
    '\n  *[_id == "siteSettings"][0] {\n    title,\n    tagline,\n    description,\n    email,\n    socialLinks[] { _key, label, url },\n    lettermark { \n  asset,\n  hotspot,\n  crop,\n  alt,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n },\n    ogImage { \n  asset,\n  hotspot,\n  crop,\n  alt,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n },\n    "resumeUrl": resume.asset->url\n  }\n': SITE_SETTINGS_QUERY_RESULT;
    '\n  *[_id == "infoPage"][0] {\n    heading,\n    bio[] {\n      ...,\n      _type == "inlineImage" => { \n  asset,\n  hotspot,\n  crop,\n  alt,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n, caption },\n      markDefs[] { ... }\n    },\n    portrait { \n  asset,\n  hotspot,\n  crop,\n  alt,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n },\n    clients,\n    seo { title, description, noIndex, image { \n  asset,\n  hotspot,\n  crop,\n  alt,\n  "lqip": asset->metadata.lqip,\n  "dimensions": asset->metadata.dimensions\n } }\n  }\n': INFO_PAGE_QUERY_RESULT;
  }
}
